### ISSUE TITLE
CentOS 7 errors

### ISSUE THREAD

**Issue by arcivanov** [sshambar/nmutils#1]
1. Performed install by copying default `/etc` into `/`.
2. `/etc/nmutils/conf/general.conf` is missing from the repository altogether
3. Disabled `IPV6INIT` on `eno1`.
4. Used simple example and changed interface names in file name to `eno1` for WAN and `eno2` for LAN respectively.

Result 
```
Jul 17 04:15:03 host ipv6-prefix[12536]: ERR: Where is dhclient-ipv6-prefix? (locate in /etc/nmutils/conf/general.conf)
Jul 17 04:15:03 host nm-dispatcher[12073]: req:4 'up' [eno1], "/etc/NetworkManager/dispatcher.d/08-ipv6-prefix": complete: failed with Script '/etc/NetworkManager/dispatcher.d/08-ipv6-prefix' exited with error status 3.
Jul 17 04:15:03 host ddns[12552]: ERR: Where is ? (locate in /etc/nmutils/conf/general.conf)
Jul 17 04:15:03 host nm-dispatcher[12073]: req:4 'up' [eno1], "/etc/NetworkManager/dispatcher.d/09-ddns": complete: failed with Script '/etc/NetworkManager/dispatcher.d/09-ddns' exited with error status 3.

```

**Comment by sshambar** [comment]
I probably should make the error message a bit clearer :)... dhclient-ipv6-prefix is a script (in source dir sbin), and should be copied to a directory in $PATH (eg /usr/local/sbin).  If you put it someplace that's not in $PATH, then you can create /etc/nmutils/conf/general.conf and add "DHSCRIPT={some dir}/dhclient-ipv6-prefix" to it.

Let me know if that doesn't work.

**Comment by arcivanov** [comment]
Ugh, thanks, I missed that part I guess :(

**Comment by arcivanov** [comment]
Yep, obviously it works if you follow the documentation :) Thanks a lot, sorry for the noise!
